[build]
  base = "meu-painel-corrigido/meu-painel"
  command = "npm run build"
  publish = "meu-painel-corrigido/meu-painel/dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; frame-src *; connect-src *;"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
